version: '3'

networks:
  monitoring:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: 
      - "--log.level=debug"
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - monitoring

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    user: root
    volumes:
      - ./loki/index:/loki/index
      - ./loki/cache:/loki/cache
      - ./config/loki/s3-config.yaml:/etc/loki/s3-config.yaml
    command:
      - "-config.file=/etc/loki/s3-config.yaml"  #/etc/loki/s3-config.yaml
      - "-config.expand-env=true"
    networks:
      - monitoring
  promtail:
    image: grafana/promtail:2.9.0
    # volumes:
    #   - ./config/promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
    #   - ./app:/app
    volumes:
      - ./config/promtail/promtail-config.yaml:/etc/promtail/config.yaml
      #로컬
      #- ../llm_AnswerGen-sroberta_hybrid/utils/utils_logs:/var/log/utils_logs:ro
      - /Users/mac/Downloads/웰체크/llm-api/llm_AnswerGen-sroberta_hybrid/utils/utils_logs:/var/log/utils_logs:ro
      #서버
      #- /home/ubuntu/llm-api/llm_AnswerGen-sroberta_hybrid/utils/utils_logs:/var/log/utils_logs:ro
      
    command: -config.file=/etc/promtail/config.yaml #-config.expand-env=true
    ports:
      - "9080:9080"
    networks:
      - monitoring
    env_file: .env

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    networks:
      - monitoring
    env_file: .env