server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: varlogs
    static_configs: #!절대경로사용
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/utils_logs/coach_assistant.log
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/utils_logs/meal_record.log
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/utils_logs/app.log