global:
  scrape_interval: 30s
  evaluation_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'fastapi'
    scrape_interval: 30s
    static_configs:
      - targets: ['host.docker.internal:5000']

  - job_name: 'node_exporter'
    scrape_interval: 30s
    static_configs:
      - targets: ['node-exporter:9100'] 